language: cpp

cache:
  directories:
    - cache

deploy:
  provider: releases
  api_key:
    secure: CdaO1tOo6qj8koBffEeD8epEZZ9dd8Idkm5MuZzlx4M0ek23i1aopXU8C5HyV5RBCNY66tf24ZYiHQDUTZye31nEvjI8cipqE4jupt7Rwyltps/h1ILVu2/8teoq/1ej05hTrUSOVWz3qFQaxUqkpjC/1u3rMH64RrPgW07a59TNzwjPtlj7fShkufLIDF7wymMwMjEd0GJVXZdGT/7NyN15btU7rvciWpAvCxdfoeeQnRaph+DeZ+DUAQ6dycZJmtSQ9V0eqtR8OFOpf8RSwGjdy0OLol2bu5/sRXH1h2UV4Tx3RgWpZiJOIvrWUekX36vvkIif4HMqx+xKK84pOouEaKyCmNjtyov36Vo5HQNtxccitedli84gGWdiFXB2wq5Gxy+ibGJn8ldHKY4gTDbYA+gBq+48AvKqfCpgbGSAEdbdk0Q8E/z67aYtNIyZgrPLNgVEbKquR8a9Ky6O3/upVuFaBNTKV8souKJTWirAxEBEE/bgxReJxJR9QY3Ti0+TTtd8ilA4+kLqV617gPePIounyxbi3s3MJVV/rtoZc0clL0e7HPNzk/0kiRewpUub4fVXL9bCeFnFNPIGLAzZAhh8fnBCD4txhhuGuJVG9cKGnhjMST2KBz+KIcjoozlIjQT7Lkpf7lVLxvXr679cl+dbo8+XdDtOClo2G3c=
  skip_cleanup: true
  file_glob: true
  file: external*.tar.bz2
  on:
    repo: comphack/external
    branch: develop

addons:
  mariadb: '10.1'

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - COMPILER_CC=clang
        - COMPILER_CXX=clang++
        - BUILD_NAME=clang
    - os: windows

before_install:
  - export ROOT_DIR=`pwd`
  - export CACHE_DIR=`pwd`/cache
  - cd ${ROOT_DIR}

script:
  - mkdir -p build && cd build && cmake -DCMAKE_INSTALL_PREFIX="${ROOT_DIR}/build/install" -DBUILD_OPTIMIZED=OFF .. && cmake --build .
  - cmake --build . --target package
